name: recyclelinkkkkkkkkkkk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

include: package:flutter_lints/flutter.yaml

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+8
  intl: ^0.19.0
  table_calendar: ^3.1.2
  image: ^3.0.1
  path_provider: ^2.0.11
  material_symbols_icons: ^4.2789.0
  file_picker: ^5.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.16
  flutter_screenutil: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" 


